#!/usr/bin/env bash

# Module: OpenClaw Environment
# Creates OpenClaw workspace directory structure

MODULE_NAME="openclaw-env"
MODULE_VERSION="2.0.0"
MODULE_DESCRIPTION="OpenClaw workspace directory structure (~/.openclaw/workspace)"
MODULE_DEPS=("system-deps")

# Source utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(dirname "$SCRIPT_DIR")/lib"

# shellcheck source=../lib/logger.sh
source "$LIB_DIR/logger.sh"
# shellcheck source=../lib/validation.sh
source "$LIB_DIR/validation.sh"

WORKSPACE_DIR="$HOME/.openclaw/workspace"

# Check if module is already installed
check_installed() {
    log_debug "Checking if $MODULE_NAME is installed"

    # Check if workspace directory exists
    if [[ ! -d "$WORKSPACE_DIR" ]]; then
        return 1
    fi

    # Check if key directories exist
    local required_dirs=("goals" "tools" "context" "hardprompts" "args" "memory" "data")

    for dir in "${required_dirs[@]}"; do
        if [[ ! -d "$WORKSPACE_DIR/$dir" ]]; then
            log_debug "Directory missing: $dir"
            return 1
        fi
    done

    log_debug "OpenClaw environment is installed"
    return 0
}

# Install the module
install() {
    log_section "Setting Up OpenClaw Environment"

    # Create workspace directory
    log_progress "Creating workspace directory: $WORKSPACE_DIR"
    mkdir -p "$WORKSPACE_DIR"
    log_success "Workspace directory created"

    # Create GOTCHA subdirectories
    local directories=(
        "goals"
        "tools"
        "context"
        "hardprompts"
        "args"
        "memory"
        "memory/logs"
        "data"
        ".tmp"
    )

    log_progress "Creating GOTCHA directory structure"
    for dir in "${directories[@]}"; do
        mkdir -p "$WORKSPACE_DIR/$dir"
        log_debug "Created: $dir"
    done
    mkdir -p "$HOME/.openclaw/extensions"
    log_success "Directory structure created"

    # Create upstream workspace template files (AGENTS.md, SOUL.md, TOOLS.md)
    log_progress "Creating upstream workspace template files"

    if [[ ! -f "$WORKSPACE_DIR/AGENTS.md" ]]; then
        cat > "$WORKSPACE_DIR/AGENTS.md" <<'EOF'
# Agents

Define your agent configurations here.
See https://docs.openclaw.ai/agents for details.

## Default Agent

The default agent uses the model configured in `~/.openclaw/openclaw.json`.
It handles general-purpose tasks across the workspace.

## Code Review Agent

A specialized agent for reviewing pull requests and code changes.
Configure with strict guidelines and security-focused prompts.

```yaml
name: code-review
model: anthropic/claude-opus-4-6
system_prompt: "You are a senior code reviewer. Focus on security, correctness, and maintainability."
```

## Research Agent

An agent optimized for deep research and information gathering.

```yaml
name: research
model: anthropic/claude-opus-4-6
system_prompt: "You are a research assistant. Provide thorough, well-sourced analysis."
```
EOF
        log_debug "Created: AGENTS.md"
    fi

    if [[ ! -f "$WORKSPACE_DIR/SOUL.md" ]]; then
        cat > "$WORKSPACE_DIR/SOUL.md" <<'EOF'
# Soul

Define the personality and behavioral guidelines for your agents.
See https://docs.openclaw.ai/soul for details.

## Core Identity

You are a knowledgeable and reliable AI assistant embedded in the OpenClaw workspace.
You help the user with software engineering, research, and productivity tasks.

## Guidelines

- Be helpful, concise, and accurate
- Follow the principle of least privilege
- Ask for clarification when instructions are ambiguous
- Prefer simple solutions over complex ones
- Always explain trade-offs when presenting options

## Communication Style

- Use clear, direct language
- Format output with markdown when helpful
- Provide code examples when relevant
- Acknowledge uncertainty rather than guessing

## Safety Boundaries

- Never execute destructive operations without confirmation
- Never expose credentials or secrets in output
- Warn about security implications of requested actions
- Respect file permissions and access controls
EOF
        log_debug "Created: SOUL.md"
    fi

    # TOOLS.md will be generated by generate-openclaw-tools-doc.sh
    # Create a placeholder if it doesn't exist
    if [[ ! -f "$WORKSPACE_DIR/TOOLS.md" ]]; then
        cat > "$WORKSPACE_DIR/TOOLS.md" <<'EOF'
# Tools

Available tools will be documented here after bootstrap completes.
Run `generate-openclaw-tools-doc.sh` to populate this file.
EOF
        log_debug "Created: TOOLS.md (placeholder)"
    fi

    log_success "Upstream template files created"

    # Create memory tools directory (placeholder for user tools)
    mkdir -p "$WORKSPACE_DIR/tools/memory"

    # Create tools/manifest.md
    log_progress "Creating tools/manifest.md"
    cat > "$WORKSPACE_DIR/tools/manifest.md" <<'EOF'
# OpenClaw Tools Manifest

This file lists all available tools in the OpenClaw workspace.

## Memory Tools (Optional)

Place any memory-related scripts in `tools/memory/`. Add their usage notes here
so the workspace stays self-documenting.

### Example

```bash
python tools/memory/your_tool.py --help
```

## Adding New Tools

To add a new tool:

1. Create the tool script in `tools/`
2. Add documentation here in manifest.md
3. Test the tool from the workspace root
4. Commit to version control
EOF

    log_success "tools/manifest.md created"

    # Set proper permissions
    log_progress "Setting permissions"
    chmod -R u+rwX "$WORKSPACE_DIR"

    # Make Python scripts executable
    find "$WORKSPACE_DIR/tools" -type f -name "*.py" -exec chmod +x {} \; 2>/dev/null || true

    log_success "Permissions set"

    # Initialize git repository (optional)
    if command -v git &>/dev/null; then
        log_progress "Initializing git repository"

        cd "$WORKSPACE_DIR" || return 1

        if ! git rev-parse --git-dir > /dev/null 2>&1; then
            git init -q

            # Create .gitignore
            cat > .gitignore <<'EOF'
# Environment
.env
*.env.local

# Temporary files
.tmp/
*.tmp
*.log

# Python
__pycache__/
*.py[cod]
*$py.class
.venv/
venv/

# Database
*.db
*.sqlite
*.sqlite3

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
EOF

            log_success "Git repository initialized"
        else
            log_info "Git repository already exists"
        fi

        cd - > /dev/null || return 1
    fi

    # Install openclaw aliases
    log_progress "Installing openclaw shell aliases"

    local ALIASES_FILE="$(dirname "$(dirname "$SCRIPT_DIR")")/bootstrap/aliases/openclaw-aliases.sh"
    local SHELL_RC="$HOME/.bashrc"

    if [[ -f "$HOME/.zshrc" ]]; then
        SHELL_RC="$HOME/.zshrc"
    fi

    if [[ -f "$ALIASES_FILE" ]]; then
        if grep -q "# OpenClaw VM - Core Aliases" "$SHELL_RC" 2>/dev/null; then
            log_info "Openclaw aliases already installed in $SHELL_RC"
        else
            log_progress "Adding openclaw aliases to $SHELL_RC"
            {
                echo ""
                echo "# OpenClaw VM - Core Aliases"
                echo "source $ALIASES_FILE"
            } >> "$SHELL_RC"
            log_success "Shell aliases installed"
        fi
    else
        log_warn "Openclaw aliases file not found, skipping"
    fi

    # Copy USER.md and BOOTSTRAP.md templates to workspace
    local TEMPLATE_DIR="$(dirname "$SCRIPT_DIR")/templates"

    if [[ -f "$TEMPLATE_DIR/USER.md.template" ]] && [[ ! -f "$WORKSPACE_DIR/USER.md" ]]; then
        cp "$TEMPLATE_DIR/USER.md.template" "$WORKSPACE_DIR/USER.md"
        log_debug "Created: USER.md (from template)"
    fi

    if [[ -f "$TEMPLATE_DIR/BOOTSTRAP.md.template" ]]; then
        local bootstrap_version="3.0.0"
        local timestamp
        timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        sed -e "s/{{ TIMESTAMP }}/$timestamp/" \
            -e "s/{{ BOOTSTRAP_VERSION }}/$bootstrap_version/" \
            "$TEMPLATE_DIR/BOOTSTRAP.md.template" > "$WORKSPACE_DIR/BOOTSTRAP.md"
        log_debug "Created: BOOTSTRAP.md (from template)"
    fi

    log_success "OpenClaw environment setup complete"
    log_info "Workspace location: $WORKSPACE_DIR"

    return 0
}

# Validate installation
validate() {
    log_progress "Validating OpenClaw environment"

    local all_valid=true

    # Check workspace directory
    if [[ -d "$WORKSPACE_DIR" ]]; then
        log_success "Workspace directory exists: $WORKSPACE_DIR"
    else
        log_error "Workspace directory not found: $WORKSPACE_DIR"
        all_valid=false
        return 1
    fi

    # Check required directories
    local required_dirs=(
        "goals"
        "tools"
        "context"
        "hardprompts"
        "args"
        "memory"
        "memory/logs"
        "data"
        ".tmp"
    )

    for dir in "${required_dirs[@]}"; do
        if [[ -d "$WORKSPACE_DIR/$dir" ]]; then
            log_success "Directory exists: $dir"
        else
            log_error "Directory missing: $dir"
            all_valid=false
        fi
    done

    # Check for key files
    local files_to_check=(
        "tools/manifest.md"
    )

    for file in "${files_to_check[@]}"; do
        if [[ -f "$WORKSPACE_DIR/$file" ]]; then
            log_success "File exists: $file"
        else
            log_warn "File missing: $file (non-critical)"
        fi
    done

    # Check if memory tools exist
    if [[ -d "$WORKSPACE_DIR/tools/memory" ]]; then
        log_success "Memory tools directory exists"

        # Count Python files
        local py_count
        py_count=$(find "$WORKSPACE_DIR/tools/memory" -name "*.py" 2>/dev/null | wc -l)
        log_info "Memory tools found: $py_count Python files"
    else
        log_warn "Memory tools directory not found"
    fi

    if [[ "$all_valid" == "true" ]]; then
        log_success "OpenClaw environment validation passed"
        return 0
    else
        log_error "OpenClaw environment validation failed"
        return 1
    fi
}

# Rollback installation
rollback() {
    log_warn "Rolling back OpenClaw environment"

    if [[ -d "$WORKSPACE_DIR" ]]; then
        log_progress "Removing workspace directory: $WORKSPACE_DIR"

        # Safety check - make sure it's our workspace
        if [[ "$WORKSPACE_DIR" == "$HOME/.openclaw/workspace" ]]; then
            rm -rf "$WORKSPACE_DIR"
            log_success "Workspace removed"
        else
            log_error "Safety check failed - unexpected workspace path: $WORKSPACE_DIR"
            return 1
        fi
    fi

    log_success "Rollback complete"

    return 0
}

# Main execution when run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-install}" in
        check)
            check_installed
            ;;
        install)
            install
            ;;
        validate)
            validate
            ;;
        rollback)
            rollback
            ;;
        *)
            echo "Usage: $0 {check|install|validate|rollback}"
            exit 1
            ;;
    esac
fi
