#!/usr/bin/env bash

# Module: Deployment Tools
# Installs Vercel, Netlify, and Supabase CLIs + MCP servers

MODULE_NAME="deployment-tools"
MODULE_VERSION="1.0.0"
MODULE_DESCRIPTION="Vercel, Netlify, Supabase CLIs and extended MCP servers"
MODULE_DEPS=("nodejs" "claude-cli")

# Source utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(dirname "$SCRIPT_DIR")/lib"

# shellcheck source=../lib/logger.sh
source "$LIB_DIR/logger.sh"
# shellcheck source=../lib/validation.sh
source "$LIB_DIR/validation.sh"

DEPLOYMENT_TOOLS_DIR="$(dirname "$SCRIPT_DIR")/deployment-tools"
MCP_CONFIG_DIR="$HOME/.config/claude"
SHELL_RC="$HOME/.zshrc"

# Check if module is already installed
check_installed() {
    log_debug "Checking if $MODULE_NAME is installed"

    local all_installed=true

    # Check Vercel CLI
    if ! validate_command "vercel"; then
        log_debug "Vercel CLI not found"
        all_installed=false
    fi

    # Check Netlify CLI
    if ! validate_command "netlify"; then
        log_debug "Netlify CLI not found"
        all_installed=false
    fi

    # Check Supabase CLI
    if ! validate_command "supabase"; then
        log_debug "Supabase CLI not found"
        all_installed=false
    fi

    if [[ "$all_installed" == "true" ]]; then
        log_debug "All deployment tools are installed"
        return 0
    else
        log_debug "Some deployment tools are missing"
        return 1
    fi
}

# Install the module
install() {
    log_section "Installing Deployment Tools"

    # Verify npm is available
    if ! validate_command "npm"; then
        log_error "npm is required but not found"
        log_info "Please install Node.js first (module 03-nodejs.sh)"
        return 1
    fi

    # Install Vercel CLI
    log_progress "Installing Vercel CLI"
    if npm install -g vercel --silent 2>/dev/null; then
        log_success "Vercel CLI installed"
    else
        log_error "Failed to install Vercel CLI"
        return 1
    fi

    # Install Netlify CLI
    log_progress "Installing Netlify CLI"
    if npm install -g netlify-cli --silent 2>/dev/null; then
        log_success "Netlify CLI installed"
    else
        log_error "Failed to install Netlify CLI"
        return 1
    fi

    # Install Supabase CLI (binary download - npm global install no longer supported)
    log_progress "Installing Supabase CLI"
    
    local install_dir="$HOME/.local/npm-global/bin"
    mkdir -p "$install_dir"
    
    local arch os_name supabase_installed=false
    os_name="$(uname -s | tr '[:upper:]' '[:lower:]')"
    case "$(uname -m)" in
        x86_64)       arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *)            arch="" ;;
    esac
    
    if [[ -n "$arch" && "$os_name" =~ ^(linux|darwin)$ ]]; then
        local url="https://github.com/supabase/cli/releases/latest/download/supabase_${os_name}_${arch}.tar.gz"
        local tmp_dir
        tmp_dir=$(mktemp -d)
        
        if curl -fsSL "$url" -o "$tmp_dir/supabase.tar.gz" 2>/dev/null && \
           tar -xzf "$tmp_dir/supabase.tar.gz" -C "$tmp_dir" 2>/dev/null && \
           mv "$tmp_dir/supabase" "$install_dir/supabase" 2>/dev/null; then
            chmod +x "$install_dir/supabase"
            supabase_installed=true
            log_success "Supabase CLI installed"
        fi
        rm -rf "$tmp_dir"
    fi
    
    if [[ "$supabase_installed" == "false" ]]; then
        log_warn "Supabase CLI installation skipped (use 'npx supabase' or install via brew)"
    fi

    # Install MCP configuration
    log_progress "Installing extended MCP server configuration"

    if [[ -f "$DEPLOYMENT_TOOLS_DIR/mcp/mcp-servers-extended.json" ]]; then
        # Create MCP config directory if it doesn't exist
        mkdir -p "$MCP_CONFIG_DIR"

        # Backup existing MCP config if it exists
        if [[ -f "$MCP_CONFIG_DIR/mcp.json" ]]; then
            log_progress "Backing up existing MCP configuration"
            cp "$MCP_CONFIG_DIR/mcp.json" "$MCP_CONFIG_DIR/mcp.json.backup.$(date +%s)"
            log_success "Backup created"
        fi

        # Copy extended MCP configuration
        cp "$DEPLOYMENT_TOOLS_DIR/mcp/mcp-servers-extended.json" "$MCP_CONFIG_DIR/mcp.json"
        log_success "MCP configuration installed"
    else
        log_warn "MCP configuration file not found, skipping"
    fi

    # Install shell aliases
    log_progress "Installing shell aliases"

    if [[ -f "$DEPLOYMENT_TOOLS_DIR/aliases/deployment-aliases.sh" ]]; then
        # Check if aliases are already installed
        if grep -q "# OpenClaw VM - Deployment Aliases" "$SHELL_RC" 2>/dev/null; then
            log_info "Deployment aliases already installed in $SHELL_RC"
        else
            log_progress "Adding deployment aliases to $SHELL_RC"
            {
                echo ""
                echo "# OpenClaw VM - Deployment Aliases"
                echo "# Generated by openclawd-config bootstrap"
                cat "$DEPLOYMENT_TOOLS_DIR/aliases/deployment-aliases.sh"
            } >> "$SHELL_RC"
            log_success "Shell aliases installed"
        fi
    else
        log_warn "Deployment aliases file not found, skipping"
    fi

    log_info ""
    log_info "Deployment tools installed successfully!"
    log_info ""
    log_info "Next steps:"
    log_info "  1. Source your shell config: source $SHELL_RC"
    log_info "  2. Authenticate with Vercel:  vercel login"
    log_info "  3. Authenticate with Netlify: netlify login"
    log_info "  4. Authenticate with Supabase: supabase login"
    log_info ""
    log_info "MCP servers require API tokens:"
    log_info "  - GitHub: export GITHUB_PAT='your-token'"
    log_info "  - Supabase: export SUPABASE_DB_URL='your-connection-string'"
    log_info "  - Brave Search: export BRAVE_API_KEY='your-key' (optional)"
    log_info ""

    return 0
}

# Validate installation
validate() {
    log_progress "Validating Deployment Tools installation"

    export PATH="$HOME/.local/npm-global/bin:$PATH"

    local all_valid=true

    # Check Vercel CLI
    if validate_command "vercel"; then
        local vercel_version
        vercel_version=$(vercel --version 2>&1 | head -n1)
        log_success "Vercel CLI installed: $vercel_version"
    else
        log_error "Vercel CLI not found"
        all_valid=false
    fi

    # Check Netlify CLI
    if validate_command "netlify"; then
        local netlify_version
        netlify_version=$(netlify --version 2>&1 | head -n1)
        log_success "Netlify CLI installed: $netlify_version"
    else
        log_error "Netlify CLI not found"
        all_valid=false
    fi

    # Check Supabase CLI
    if validate_command "supabase"; then
        local supabase_version
        supabase_version=$(supabase --version 2>&1 | head -n1)
        log_success "Supabase CLI installed: $supabase_version"
    else
        log_error "Supabase CLI not found"
        all_valid=false
    fi

    # Check MCP configuration
    if [[ -f "$MCP_CONFIG_DIR/mcp.json" ]]; then
        # Validate JSON syntax
        if jq empty "$MCP_CONFIG_DIR/mcp.json" 2>/dev/null; then
            local server_count
            server_count=$(jq '.mcpServers | length' "$MCP_CONFIG_DIR/mcp.json" 2>/dev/null)
            log_success "MCP configuration valid: $server_count servers configured"
        else
            log_error "MCP configuration is invalid JSON"
            all_valid=false
        fi
    else
        log_warn "MCP configuration not found: $MCP_CONFIG_DIR/mcp.json"
    fi

    # Check shell aliases
    if grep -q "# OpenClaw VM - Deployment Aliases" "$SHELL_RC" 2>/dev/null; then
        log_success "Shell aliases installed in $SHELL_RC"
    else
        log_warn "Shell aliases not found in $SHELL_RC"
    fi

    if [[ "$all_valid" == "true" ]]; then
        log_success "Deployment Tools validation passed"
        return 0
    else
        log_error "Deployment Tools validation failed"
        return 1
    fi
}

# Rollback installation
rollback() {
    log_warn "Rolling back Deployment Tools installation"

    # Uninstall npm packages
    log_progress "Uninstalling Vercel CLI"
    npm uninstall -g vercel --silent 2>/dev/null || true

    log_progress "Uninstalling Netlify CLI"
    npm uninstall -g netlify-cli --silent 2>/dev/null || true

    log_progress "Uninstalling Supabase CLI"
    npm uninstall -g supabase --silent 2>/dev/null || true

    # Restore MCP config backup if it exists
    if [[ -f "$MCP_CONFIG_DIR/mcp.json" ]]; then
        local latest_backup
        latest_backup=$(ls -t "$MCP_CONFIG_DIR"/mcp.json.backup.* 2>/dev/null | head -n1)

        if [[ -n "$latest_backup" ]]; then
            log_progress "Restoring MCP configuration from backup"
            cp "$latest_backup" "$MCP_CONFIG_DIR/mcp.json"
            log_success "MCP configuration restored"
        else
            log_progress "Removing MCP configuration (no backup found)"
            rm -f "$MCP_CONFIG_DIR/mcp.json"
        fi
    fi

    # Remove shell aliases
    if [[ -f "$SHELL_RC" ]]; then
        log_progress "Removing shell aliases from $SHELL_RC"

        # Create a temp file without the deployment aliases section
        local temp_file
        temp_file=$(mktemp)

        awk '
            /# OpenClaw VM - Deployment Aliases/ { skip=1; next }
            skip && /^[^#]/ && /^$/ { skip=0; next }
            !skip { print }
        ' "$SHELL_RC" > "$temp_file"

        mv "$temp_file" "$SHELL_RC"
        log_success "Shell aliases removed"
    fi

    log_success "Rollback complete"

    return 0
}

# Main execution when run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-install}" in
        check)
            check_installed
            ;;
        install)
            install
            ;;
        validate)
            validate
            ;;
        rollback)
            rollback
            ;;
        *)
            echo "Usage: $0 {check|install|validate|rollback}"
            exit 1
            ;;
    esac
fi
